spring.application.name=product-service
server.port=8084

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB
spring.data.mongodb.uri=mongodb://root:123456@localhost:27017/shop?authSource=admin

# Nacos
spring.cloud.nacos.discovery.server-addr=localhost:8848

# Actuator
management.endpoints.web.exposure.include=*

# tell Seata how to find server
seata.registry.type=file
seata.config.type=file

seata.service.vgroup-mapping.default_tx_group=default
seata.service.grouplist.default=127.0.0.1:8091